// SkyPark location options for tickets

export const LOCATION_OPTIONS = [
  "Admin Office",
  "Admission Restrooms",
  "Admissions",
  "Adventure Center",
  "Adventure Zipline",
  "Arrow's Adventure",
  "B-Rail",
  "Bike Park",
  "Billy's BBQ House",
  "Billy's Restrooms",
  "Birthday Room - Enchanted Forest",
  "Bridal Suite",
  "Campground",
  "CoachWorks",
  "Creekside",
  "Fantasy Forest",
  "Frozen Falls",
  "Gingerbread House Bakery",
  "Kringle's Coffee & Gifts",
  "Magic Tree Bouldering Room",
  "Merry Moments Photo Shoppe",
  "Park Wide",
  "Pedal Pub",
  "Reindeer Adoption Room",
  "Royal Encampment at Sky Trading",
  "Safety/Security",
  "Santa's House",
  "Santa's Village Mining Co",
  "Santa's Workshop",
  "Serrano Archery Range",
  "Silver Bells Arena",
  "Silver Bells Arena Concessions",
  "Sky Trading Co",
  "St. Nick's Patio and Grille",
  "St. Nicks Restrooms",
  "Terrace",
  "The Lunchbox",
  "The Reindeer Room (Speakeasy)",
  "Top of the World",
  "Toy Test Track",
  "Upper Restrooms",
  "Village Green Breakroom",
  "Zipline",
  "Other",
  "N/A",
] as const;

export type Location = typeof LOCATION_OPTIONS[number];

export function getLocations(): readonly string[] {
  return LOCATION_OPTIONS;
}
